language: php
php:
  - 7.1
install:
  - composer self-update
  - composer install
before_script:
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:update --force --env=test
  - php app/console app:create-students --env=test
script:
  - phpunit -c app
  - php vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 src
  - php vendor/phpmd/phpmd/src/bin/phpmd src text cleancode,codesize,design,unusedcode
  - php vendor/sebastian/phpcpd/phpcpd src -n -q