language: php
php:
  - 7.1
install: composer install
before_script:
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:schema:update --force
  - php bin/console app:create-students
script:
  - phpunit -c app
  - php vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 src
  - php vendor/phpmd/phpmd/src/bin/phpmd src text cleancode,codesize,design,unusedcode
  - php vendor/sebastian/phpcpd/phpcpd src -n -q