# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: StudentBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    slug_helper:
        class: StudentBundle\Service\SlugHelper

    students_service:
        class: StudentBundle\Service\StudentService
        arguments: ["@doctrine.orm.entity_manager", "@slug_helper"]